name: Gatling Load Testing

on:
  push:
    branches: [ feat/load-testing ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests/load-testing
    env:
      API_URL: ${{vars.API_URL}}
      TARGET_USER_RATE: ${{vars.GATLING_TARGET_USER_RATE}}
      RAMP_DURATION: ${{vars.GATLING_RAMP_DURATION}}
      PEAK_USERS: ${{vars.GATLING_PEAK_USERS}}
      STRESS_DURATION: ${{vars.GATLING_STRESS_DURATION}}

    steps:
      - uses: actions/checkout@v4

      - name: Install Java and Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          cache-directory-path: ./tests/load-testing/pom.xml

#      - run: mvn install
#
#      - name: Run Gatling tests
#        run: mvn gatling:test
      - name: Build mock reports
        run: |
          mkdir -p tests/load-testing/target/vvasimulation-20240409082410584
          echo "Test" > tests/load-testing/target/vvasimulation-20240409082410584/test.txt

      - uses: actions/upload-artifact@v3
        with:
          name: gatling-results
          path: tests/load-testing/target

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: gatling-results
          path: gatling-results

      - name: Get Gatling history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
          repository: NabinKawan/allure-report
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Generate report
        run: |
          mkdir build
          cp -r gh-pages/gatling/ build/ || true
          cp -r gatling-results/*[^lastRun.txt] build/
          copied_folder=$(basename $(ls -d gatling-results/*[^lastRun.txt]))
          echo "$copied_folder" > build/tests.txt      

      - name: Deploy report to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          repository-name: NabinKawan/allure-report
          branch: gh-pages
          folder: build
          target-folder: gatling